# Generated by Django 6.0.3 on 2026-03-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0005_remove_doctor_slug"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proceeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuss_code", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=250)),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
