# Generated by Django 6.0.3 on 2026-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proceeding", "0002_alter_proceeding_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceeding",
            name="proceeding_type",
            field=models.CharField(
                choices=[("Inquiry", "Consulta"), ("Proceeding", "Procedimento")],
                default="Proceeding",
                max_length=20,
            ),
        ),
    ]
