# Generated by Django 6.0.3 on 2026-03-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proceeding", "0003_proceeding_proceeding_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceeding",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="proceeding",
            name="tuss_code",
            field=models.IntegerField(
                choices=[
                    (81000057, "81000057 - Consulta Odontológica Inicial"),
                    (81000049, "81000049 - Consulta Odontológica de Urgência"),
                    (82001553, "82001553 - Atividade Educativa em Saúde Bucal"),
                    (82000425, "82000425 - Condicionamento em Odontologia"),
                    (
                        85100021,
                        "85100021 - Amputação Radicular com Obturação Retrógada",
                    ),
                    (
                        85100030,
                        "85100030 - Amputação Radicular sem Obturação Retrógada",
                    ),
                    (
                        85100048,
                        "85100048 - Apicetomia Birradiculares com Obturação Retrógada",
                    ),
                    (
                        85100056,
                        "85100056 - Apicetomia Birradiculares sem Obturação Retrógada",
                    ),
                    (
                        85100064,
                        "85100064 - Apicetomia Multirradiculares com Obturação Retrógada",
                    ),
                    (
                        85100072,
                        "85100072 - Apicetomia Multirradiculares sem Obturação Retrógada",
                    ),
                    (
                        85100080,
                        "85100080 - Apicetomia Unirradiculares com Obturação Retrógada",
                    ),
                    (
                        85100099,
                        "85100099 - Apicetomia Unirradiculares sem Obturação Retrógada",
                    ),
                    (85100102, "85100102 - Aprofundamento/Aumento de Vestíbulo"),
                    (85100110, "85100110 - Aumento de Coroa Clínica"),
                    (85100129, "85100129 - Biópsia de Boca"),
                    (85100137, "85100137 - Bridectomia"),
                    (85100145, "85100145 - Bridotomia"),
                    (
                        85400017,
                        "85400017 - Capeamento Pulpar Direto - Excluindo Restauração Final",
                    ),
                    (85100226, "85100226 - Cirurgia para Exostose Maxilar"),
                    (85100234, "85100234 - Cirurgia para Torus Mandibular"),
                    (85100242, "85100242 - Cirurgia para Torus Palatino"),
                    (85100250, "85100250 - Cirurgia Periodontal a Retalho"),
                    (85400033, "85400033 - Colagem de Fragmentos Dentários"),
                    (85300012, "85300012 - Coroa Unitária Provisória com ou sem Pino"),
                    (
                        85100439,
                        "85100439 - Exérese de Lipoma na Região Buco-Maxilo-Facial",
                    ),
                    (
                        85100455,
                        "85100455 - Exérese de Pequenos Cistos de Mandíbula/Maxila",
                    ),
                    (85100498, "85100498 - Frenectomia Labial"),
                    (85100501, "85100501 - Frenectomia Lingual"),
                    (85100510, "85100510 - Frenotomia Labial"),
                    (85100528, "85100528 - Frenotomia Lingual"),
                    (85100536, "85100536 - Gengivectomia"),
                    (85100544, "85100544 - Gengivoplastia"),
                    (85100919, "85100919 - Pulpotomia"),
                    (
                        85300047,
                        "85300047 - Reabilitação com Coroa Total Metálica Unitária",
                    ),
                    (
                        85300055,
                        "85300055 - Reabilitação com Núcleo Metálico Fundido/Pré-Fabricado",
                    ),
                    (
                        85300063,
                        "85300063 - Reabilitação com Restauração Metálica Fundida (RMF) Unitária",
                    ),
                    (85300071, "85300071 - Recimentação de Peça/Trabalho Protético"),
                    (85100935, "85100935 - Reconstrução de Sulco Gengivo-Labial"),
                    (
                        85100943,
                        "85100943 - Redução Cruenta de Fratura Alvéolo Dentária",
                    ),
                    (
                        85100951,
                        "85100951 - Redução Incruenta de Fratura Alvéolo Dentária",
                    ),
                    (
                        85100960,
                        "85100960 - Reimplante de Dente Avulsionado com Contenção",
                    ),
                    (85400157, "85400157 - Remoção de Corpo Estranho Intracanal"),
                    (85100978, "85100978 - Remoção de Dentes Inclusos / Impactados"),
                    (
                        85100986,
                        "85100986 - Remoção de Dentes Semi-Inclusos / Impactados",
                    ),
                    (
                        82001430,
                        "82001430 - Remoção de Fatores de Retenção de Biofilme Dental",
                    ),
                    (85400165, "85400165 - Remoção de Núcleo Intracanal"),
                    (85300080, "85300080 - Remoção de Peça/Trabalho Protético"),
                    (85400173, "85400173 - Restauração em Amálgama"),
                    (85400190, "85400190 - Restauração em Ionômero de Vidro"),
                    (85400211, "85400211 - Restauração em Resina Fotopolimerizável"),
                    (85101010, "85101010 - Tratamento de Abscesso Periodontal"),
                    (85101028, "85101028 - Tratamento de Alveolite"),
                    (85101044, "85101044 - Tratamento de Odontalagia Aguda"),
                    (85400505, "85400505 - Tratamento Endodôntico Birradicular"),
                    (85400513, "85400513 - Tratamento Endodôntico Multirradicular"),
                    (85400521, "85400521 - Tratamento Endodôntico Unirradicular"),
                    (85101079, "85101079 - Ulectomia"),
                    (85101087, "85101087 - Ulotomia"),
                ]
            ),
        ),
    ]
