# Generated by Django 6.0.3 on 2026-03-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
