# Generated by Django 6.0.3 on 2026-03-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(
                default="<django.db.models.fields.CharField>-<django.db.models.fields.CharField>",
                max_length=61,
            ),
        ),
    ]
