# Generated by Django 6.0.3 on 2026-03-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_alter_doctor_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="slug",
        ),
    ]
